[Pytorch Pytest] Use PyTorch to set HIP_VISIBLE_DEVICES (#2211)
HIP_VISIBLE_DEVICES is now determined using PyTorch, so that
PyTorch pytest can correctly run on multi-gpu nodes.

Additional features:
- Respects if HIP_VISIBLE_DEVICES was set before and only selects
  GPUs from that pool
- Only allows to select GPUs that are also supported by the current
   PyTorch build

Implementation note:
- Gpu detection using pytorch must be done in a subprocess so
that HIP_VISIBLE_DEVICES can be set correctly for pytest
(must happen before the torch import)

Why the change?
Old version used offload-arch that sees more gpus than pytorch resulting in pytest failing with:
RuntimeError: HIP_VISIBLE_DEVICES contains more devices than ROCR_VISIBLE_DEVICES


---------

Co-authored-by: Mika Laitio <mika.laitio@amd.com>