Revert "feat(ci): Add --projects flag for selective builds" (#6641)
Reverts PR: ROCm/TheRock#6451
Fixes Issue: https://github.com/ROCm/rocm-libraries/issues/9535
```
hipsparselt_error: Cannot read /__w/TheRock/TheRock/build/bin/../lib/hipsparselt/library/TensileLibrary_lazy_gfx942.dat (or .zlib variant): No such file or directory
hipsparselt_error: Could not load /__w/TheRock/TheRock/build/bin/../lib/hipsparselt/library/TensileLibrary_lazy_gfx942.dat
hipModuleLoad failed: /__w/TheRock/TheRock/build/bin/../lib/hipsparselt/library/Kernels.so-000-gfx942.hsaco
 error: file not found
hipModuleLoad failed: /__w/TheRock/TheRock/build/bin/../lib/hipsparselt/library/Kernels.so-000-gfx942-xnack-.hsaco
 error: file not found
hipModuleLoad failed: /__w/TheRock/TheRock/build/bin/../lib/hipsparselt/library/Kernels.so-000-gfx942-xnack+.hsaco
 error: file not found
hipsparselt_error: Could not initialize Tensile library
There are no solutions for this problem size
```

hipsparselt test passed in CI
https://github.com/ROCm/TheRock/actions/runs/29564486058/job/87847577105?pr=6641
which was failed in original PR.