fix(package): update rocpd & roctx python versions to include 3.14 (#7350)
## Motivation

In ROCm 7.14 whl and tarballs, rocpd and roctx need to support multiple
python versions. Looks like it's been limited to 3.10-3.13. When users
installed onto Ubuntu 26.04 where the default python version is 3.14,
they get an error:

```rocpd --help
Traceback (most recent call last):
  File "/opt/venv/lib/python3.14/site-packages/_rocm_sdk_devel/bin/rocpd", line 74, in <module>
    main()
    ~~~~^^
  File "/opt/venv/lib/python3.14/site-packages/_rocm_sdk_devel/bin/rocpd", line 46, in main
    raise ImportError(
    ...<5 lines>...
    )
ImportError: rocpd not supported for Python version 3.14 (sys.executable='/opt/venv/bin/python3').
rocpd supported python versions: 3.10, 3.11, 3.12, 3.13
```

## Technical Details

Digging into TheRock build, it looks like the python versions used are
defined in `DIST_PYTHON_EXECUTABLES`. However, the manylinux image SHA
TheRock is using is slightly old, and only has up to 3.13 in
/opt/python.

To add 3.14, we would need to:
1) Update the manylinux image SHA to something newer, and then update
`DIST_PYTHON_EXECUTABLES` or
2) Just use the `/opt/python-shared/cp314-cp314/bin/python3` that rocgdb
is using

Opting for 2, to minimize changes. 
We may need an additional rocprofiler-sdk change to make the python 3.14
discoverable since CMake is old in manylinux image.
https://github.com/ROCm/rocm-systems/pull/10198

Update 10/6: we don't need to update the SHA after all. So this PR just
includes 3.14 builds for roctx & rocpd.

Addresses ISSUE ID https://github.com/ROCm/TheRock/issues/7398

## Test Plan

Check the build artifacts to see if python3.14 is now usable with rocpd.
There was discussion to add rocpd tests to TheRock, but there are
additional issues that need to be resolved, before those tests can be
added.

## Test Result

rocpd should be usable with python 3.14

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/TheRock/blob/main/CONTRIBUTING.md.