Fix wrong hip compiler in subproject
If CMAKE_HIP_COMPILER is not set, sub-projects will incorrectly find
/opt/rocm*/lib/llvm/bin/clang++.

This may causes a build failure if the installed compiler is missing features
needed by the sub-project.

I was seeing:

```
FAILED: catch_tests/unit/rtc/CMakeFiles/RTC.dir/RtcFunctions.cpp.o
/opt/rocm-7.1.1/lib/llvm/bin/clang++  ...
In file included from .../rocm-systems/projects/hip-tests/catch/unit/rtc/RtcFunctions.cpp:14:
In file included from .../core/clr/dist/include/hip/hip_fp16.h:13:
.../core/clr/dist/include/hip/amd_detail/amd_hip_fp16.h:952:21: error: use of undeclared identifier '__builtin_elementwise_exp10'
  952 |   return __half_raw{__builtin_elementwise_exp10(static_cast<__half_raw>(x).data)};
      |                     ^
```