Switch copy_release.yml to operate on multi-arch v4/whl/ subdir (#5944)
> [!IMPORTANT]
> This is stacked against https://github.com/ROCm/TheRock/pull/5892. I
could split into a separate PR but the docs will be outdated
(differently) if we do that.

## Motivation

Progress on https://github.com/ROCm/TheRock/issues/3340, deleting or
migrating away from per-family CI/CD to multi-arch CI/CD.

This will let us copy multi-arch release packages from the nightly
release bucket (https://rocm.nightlies.amd.com/whl-multi-arch/) to the
dev release bucket (https://rocm.devreleases.amd.com/whl-multi-arch/)
for use with workflows like
[`.github/workflows/test_pytorch_wheels.yml`](https://github.com/ROCm/TheRock/blob/main/.github/workflows/test_pytorch_wheels.yml).

See
https://github.com/ROCm/TheRock/actions/runs/27648661730/job/81776901236
for an example of where a "dev" pytorch build used "nightly" rocm
packages, uploaded its dev packages to the dev index, and was unable to
access the rocm packages under the test index during the test step:
```
ERROR: Could not find a version that satisfies the requirement rocm==7.14.0a20260615 (from torch)
```

## Technical Details

I decided to remove inputs that I don't currently expect to vary from
run to run (subfolder, input bucket, output bucket, etc.). This will
limit what the workflow can do, and I think that's a good thing. I don't
want to grant anyone the ability to copy arbitrary files across buckets
and subfolders (without working for it a bit ;P). If we change from
`v4/whl/` to a different subdirectory then this workflow may not work
without edits anyways (like how per-family v2/ did not port to
multi-arch v4/).

## Test Plan

* Real test run:
https://github.com/ROCm/TheRock/actions/runs/27847254225/job/82418942474
  * 11GB of rocm packages (for one nightly release, one python version)
* 16.7GB of torch packages (for one nightly release, one python version)
  * 0GB of jax packages (not uploaded in nightly releases yet)
* Dry-run:
https://github.com/ROCm/TheRock/actions/runs/27726169154/job/82022840938
  * rocm:
    ```
(dryrun) copy:
s3://therock-nightly-python/v4/whl/rocm-7.14.0a20260617.tar.gz to
s3://therock-dev-python/v4/whl/rocm-7.14.0a20260617.tar.gz
(dryrun) copy:
s3://therock-nightly-python/v4/whl/rocm_profiler-7.14.0a20260617-py3-none-linux_x86_64.whl
to
s3://therock-dev-python/v4/whl/rocm_profiler-7.14.0a20260617-py3-none-linux_x86_64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/rocm_sdk_core-7.14.0a20260617-py3-none-linux_x86_64.whl
to
s3://therock-dev-python/v4/whl/rocm_sdk_core-7.14.0a20260617-py3-none-linux_x86_64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/rocm_sdk_core-7.14.0a20260617-py3-none-win_amd64.whl
to
s3://therock-dev-python/v4/whl/rocm_sdk_core-7.14.0a20260617-py3-none-win_amd64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/rocm_sdk_devel-7.14.0a20260617-py3-none-linux_x86_64.whl
to
s3://therock-dev-python/v4/whl/rocm_sdk_devel-7.14.0a20260617-py3-none-linux_x86_64.whl
    ```
  * torch:
    ```
(dryrun) copy:
s3://therock-nightly-python/v4/whl/amd_torch_device_gfx1010-2.10.0+rocm7.14.0a20260617-cp312-cp312-linux_x86_64.whl
to
s3://therock-dev-python/v4/whl/amd_torch_device_gfx1010-2.10.0+rocm7.14.0a20260617-cp312-cp312-linux_x86_64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/amd_torch_device_gfx1010-2.10.0+rocm7.14.0a20260617-cp312-cp312-win_amd64.whl
to
s3://therock-dev-python/v4/whl/amd_torch_device_gfx1010-2.10.0+rocm7.14.0a20260617-cp312-cp312-win_amd64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/amd_torch_device_gfx1010-2.11.0+rocm7.14.0a20260617-cp312-cp312-linux_x86_64.whl
to
s3://therock-dev-python/v4/whl/amd_torch_device_gfx1010-2.11.0+rocm7.14.0a20260617-cp312-cp312-linux_x86_64.whl
(dryrun) copy:
s3://therock-nightly-python/v4/whl/amd_torch_device_gfx1010-2.11.0+rocm7.14.0a20260617-cp312-cp312-win_amd64.whl
to
s3://therock-dev-python/v4/whl/amd_torch_device_gfx1010-2.11.0+rocm7.14.0a20260617-cp312-cp312-win_amd64.whl
    ```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.