link correct version of hsa-runtime with c10_hip
link the version of hsa-runtime64 that is searched
by LoadHIP.cmake instead of relying to it to be linked
as an amdhip64 dependency without specifying the location.

This fixes an error where the wrong version of library could
be tried to be linked causing unresolved symbol errors:

  TheRock/build/dist/rocm/lib/libamdhip64.so.6.5.25171-31afa624a:
  undefined reference tohsa_amd_vmem_map@ROCR_1'

Fixes: https://github.com/ROCm/TheRock/issues/474

Signed-off-by: Mika Laitio <mika.laitio@amd.com>