Revert "Simplify s3_client auth/credentials setup using boto3 (#4051)"
This reverts commit 01e31f77e1c02640f01e1646717bd63565f3ea35. The
changes seem to break the `Validate Artifact Structure` workflow which
is failing during fetch:

```
Traceback (most recent call last):
  File "/home/runner/_work/TheRock/TheRock/./build_tools/fetch_artifacts.py", line 386, in <module>
    main(sys.argv[1:])
  File "/home/runner/_work/TheRock/TheRock/./build_tools/fetch_artifacts.py", line 382, in main
    run(args)
  File "/home/runner/_work/TheRock/TheRock/./build_tools/fetch_artifacts.py", line 210, in run
    available_artifacts = list_artifacts_for_group(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/TheRock/TheRock/./build_tools/fetch_artifacts.py", line 88, in list_artifacts_for_group
    all_artifacts = backend.list_artifacts()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/TheRock/TheRock/build_tools/_therock_utils/artifact_backend.py", line 253, in list_artifacts
    for page in page_iterator:
                ^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/paginate.py", line 272, in __iter__
    response = self._make_request(current_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/paginate.py", line 360, in _make_request
    return self._method(**current_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/context.py", line 123, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/endpoint.py", line 118, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/endpoint.py", line 195, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/endpoint.py", line 131, in create_request
    self._event_emitter.emit(
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/signers.py", line 200, in sign
    auth.add_auth(request)
  File "/home/runner/_work/_tool/Python/3.12.13/x64/lib/python3.12/site-packages/botocore/auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
Error: Process completed with exit code 1.
```
https://github.com/ROCm/TheRock/actions/runs/23274411292/job/67680316698