[bkc] Cherry-pick "fix(rocjitsu): package hotswap translator dependency (#7371)" (#7459)
This is a cherry-pick of https://github.com/ROCm/TheRock/pull/7371 to
address https://github.com/ROCm/rocm-systems/issues/10164 which is also
occurring on the BKC release branch at
https://github.com/ROCm/rockrel/actions/runs/32165066093/job/95802835561:
```
88/89 Test #88: therock-validate-shared-lib-libhsa_hotswap_rocjitsu.so ...........***Failed    0.02 sec
Validating shared library: /__w/rockrel/rockrel/build/emulation/rocjitsu/dist/lib/libhsa_hotswap_rocjitsu.soTraceback (most recent call last):
  File "/__w/rockrel/rockrel/build_tools/validate_shared_library.py", line 27, in <module>
    main(sys.argv[1:])
  File "/__w/rockrel/rockrel/build_tools/validate_shared_library.py", line 23, in main
    run(args)
  File "/__w/rockrel/rockrel/build_tools/validate_shared_library.py", line 15, in run
    so = ctypes.cdll.LoadLibrary(shared_lib)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/cp312-cp312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: librocjitsu_gfx1250_b0_to_a0.so.0: cannot open shared object file: No such file or directory
```

Co-authored-by: Kunwar Grover <groverkss@gmail.com>