Add third-party/elfio
Add third-party/elfio project for therock
to allow profiler tools like rocprofiler-sdk to
use it from standard location instead of each subproject
downloading and building it separately.
their own build phase.

This allows standardizasing to single version of these
dependencies and to have a centralized place to fix
problems.

In addition latest release has been patched for the following gcc build
error:

therock/build/third-party/elfio/build_elfio/
dist/include/elfio/elf_types.hpp:30:20:
error: unknown type name 'uint16_t'
9.5	   30 | using Elf_Half   = uint16_t;

fixes: https://github.com/ROCm/TheRock/issues/3517

Signed-off-by: Mika Laitio <mika.laitio@amd.com>