Revert "[ci] Fixing dep rpm packages for forked upload (#5066)"
This reverts commit fc4e6be70f49f6de3d562f71899314fbe2709d7d. Starting
from that commit, the `Configure AWS Credentials` steps in the native
Linux packages build jobs (deb and rpm) fail with

```
Error: Could not assume role with OIDC: Not authorized to perform sts:AssumeRoleWithWebIdentit
```

due to assuming a non-existing role `*:role/therock-` (missing release
type):
https://github.com/ROCm/TheRock/actions/runs/25931650380/job/76257228730